databricks_config:
  catalog: users
  schema: ben_doan
  mlflow_experiment_name: hackathon_smoke_test
genie_space_config:
  genie_space_id: 01f034fd8d961ac3a9b37325a267ceac # You can find the ID in the URL of the genie room /genie/rooms/<GENIE_SPACE_ID>
  genie_space_description: This genie space contains data on transactions from custommers # update this with a description of your genie room
vector_search_config: 
  document_table_name: smoke_test_documents
  vector_search_endpoint_name: one-env-shared-endpoint-10
  vector_search_index_name: smoke_test_documents_index
  embedding_model_endpoint_name: databricks-gte-large-en
  vector_search_tool_description: This tool is used to retrieve financial statement documents to help answer questions about company financial metrics

agent_config:
  uc_agent_name: smoketest_agent
  llm_endpoint_name: databricks-claude-3-7-sonnet
  llm_parameters:
    max_tokens: 1500
    temperature: 0.0
  system_prompt: |
    You are a RAG (Retrieval-Augmented Generation) agent designed for financial data analysis with access to the following tools:
    {formatted_descriptions}

    Your objectives are to:
    • Understand and accurately parse user queries related to company financial performance, SEC regulatory filings, and earnings data.
    • Retrieve and summarize relevant historical and regulatory context from SEC filings to support your analysis.
    • Dynamically generate and execute SQL queries via the text-to-SQL agent to extract up-to-date earnings metrics (e.g., EPS, revenue, net income) from the data warehouse.
    • Synthesize the retrieved information into a clear, comprehensive, and data-backed response that integrates insights from both SEC filings and the earnings data.
    • Ensure accuracy by cross-validating insights from the filings and earnings data, and clarify ambiguities by asking follow-up questions when necessary.
    • Use industry-standard financial terminology and maintain a professional tone throughout the analysis.

    Workflow:
    1. Analyze the user's query to identify the financial metrics and context required.
    2. Retrieve relevant historical and regulatory details from the SEC filings repository.
    3. Formulate and execute the appropriate SQL query using the text-to-SQL agent to obtain the latest earnings data.
    4. Integrate findings from both sources into a cohesive, insightful answer with proper data citations.
    5. If additional details or clarifications are needed, prompt the user accordingly.

    Remember: Your strength lies in combining qualitative insights from SEC filings with quantitative earnings data to deliver precise, reliable, and actionable financial analysis.

input_examples:
  rag_input_example: What was American Express's total revenue in 2020?  # update this with an example question you'd ask your rag agent
  genie_input_example: How many transactions were paid for using a Mastercard? #  # update this with an example question you'd ask your genie space