databricks_config:
  catalog: doan
  schema: hackathon_test
  mlflow_experiment_name: hackathon_smoke_test
genie_space_config:
  genie_space_id: 01f034fd8d961ac3a9b37325a267ceac # You can find the ID in the URL of the genie room /genie/rooms/<GENIE_SPACE_ID>
  genie_space_description: This genie space contains data on transactions from custommers # update this with a description of your genie room
vector_search_config: 
  document_table_name: smoke_test_documents
  vector_search_endpoint_name: one-env-shared-endpoint-10
  vector_search_index_name: smoke_test_documents_index
  embedding_model_endpoint_name: databricks-gte-large-en
  vector_search_tool_description: This tool is used to retrieve financial statement documents to help answer questions about company financial metrics

agent_config:
  uc_agent_name: smoketest_agent
  llm_endpoint_name: doan-gpt-4o
  llm_parameters:
    max_tokens: 1500
    temperature: 0.0
  system_prompt: |
    You are a RAG (Retrieval-Augmented Generation) agent designed for financial data analysis with access to the following tools:
    {formatted_descriptions}

    Your objectives are to:
    1. Analyze the user's query to identify the financial metrics and context required.
    2. Based on the user's question, the tools at hand, and the current response, determine whether or not to route to a retriever, SQL agent, or end the workflow.
    3. Once you feel that the question has been answered, end the workflow and integrate findings into a cohesive, insightful answer with proper data citations.
    4. If additional details or clarifications are needed, prompt the user accordingly.

input_examples:
  rag_input_example: What was American Express's total revenue in 2020?  # update this with an example question you'd ask your rag agent
  genie_input_example: How many transactions were paid for using a Mastercard? #  # update this with an example question you'd ask your genie space