databricks_resources:
  llm_endpoint_name: databricks-claude-3-7-sonnet
  vector_search_endpoint_name: one-env-shared-endpoint-1
  model_name: rag_agent

input_example:
  messages:
  - content: "What was American Express reported revenue in 2022?"
    role: user

rag_agent_llm_config:
  llm_endpoint_name: databricks-claude-3-7-sonnet
  llm_parameters:
    max_tokens: 1500
    temperature: 0.01
  llm_prompt_template: "You are an assistant that answers questions.
        Use only the information in context to answer the question at the end.
        Some pieces of context may be irrelevant, in which case you should not use them to form the answer.
        Only answer question from the context, do not add anymore information. 
        If the question is not relevant to COVID Trials, only respond with 'Irrelevant Question'.
        \n\nContext: {context},
        \n\nQuestion:{query}"
  llm_prompt_template_variables:
  - context
  - query

retriever_config:
  vector_search_endpoint_name: one-env-shared-endpoint-1
  vector_search_index: felixflory.databricks_genai_hackathon.sec_rag_docs_pages_index
  workspace_url_environment_var: DATABRICKS_HOST
  pat_environment_var: DATABRICKS_TOKEN
  client_id_environment_var: VECTOR_SEARCH_CLIENT_ID
  client_secret_environment_var: VECTOR_SEARCH_CLIENT_SECRET
  text_column: "content_chunked"
  retrieve_columns: ["content_chunked"]
  parameters:
      k: 3
      query_type: ann