uc_catalog: doan
uc_schema: databricks_genai_hackathon
raw_data_volume: raw_data
vector_search_endpoint_name: one-env-shared-endpoint-15
embedding_model_endpoint_name: databricks-bge-large-en
secret_scope: doan
genie_space_id: 01f00c360aa7147aa93f081d65b4c8e5
mlflow_experiment_base_path: 'Users/ben.doan@databricks.com/mlflow_experiments'
mlflow_experiment_name: databricks_genai_hackathon

llm_endpoint_names: 
  # - databricks-llama-4-maverick
  - databricks-claude-3-7-sonnet
  #- ASK-BEFORE-USE-fflory-gpt-4o
  # - ASK-BEFORE-USE-fflory-claude-3-7

vector_search_attributes:
  id_1: # use the table name (not fully qualified) and the optional values will be imputed and validated
    table_name: sec_rag_docs_pages
    # index_name: 'felixflory.databricks_genai_hackathon.sec_rag_docs_pages_index'
    primary_key: chunk_id
    embedding_source_column: content_chunked
    url: "https://raw.githubusercontent.com/fflory/databricks_genai_hackathon/main/data/sec_rag_docs_pages.snappy.parquet"
    # local_path: "/Volumes/felixflory/databricks_genai_hackathon/raw_data/sec_rag_docs_pages.snappy.parquet"


genie_tables:
  id_1:
    table_name: balance_sheet
    # name: balance_sheet
    url: "https://raw.githubusercontent.com/fflory/databricks_genai_hackathon/main/data/balance_sheet.parquet"
  id_2:
    table_name: income_statement
    # name: income_statement
    url: "https://raw.githubusercontent.com/fflory/databricks_genai_hackathon/main/data/income_statement.parquet"


eval_tables:
  id_1:
    table_name: sec_rag_eval_data
    # fqn: felixflory.databricks_genai_hackathon.sec_rag_eval_data
    url: "https://raw.githubusercontent.com/fflory/databricks_genai_hackathon/main/data/sec_rag_eval_data.snappy.parquet"
    # local_path: "/Volumes/felixflory/databricks_genai_hackathon/raw_data/sec_rag_eval_data.snappy.parquet"
