databricks_config:
  catalog: doan
  schema: finance_bench
  mlflow_experiment: doan_sec_hackathon_agent
  pat_token_secret_scope: doan-demos
  pat_token_secret_key: databricks-pat
  eval_table_name: hackathon_eval_questions
  model_name: sec_agent

planning_agent_config:
  llm_config:
    llm_endpoint_name: databricks-claude-sonnet-4
    llm_parameters:
      max_tokens: 500
      temperature: 0.0
      parallel_tool_calls: false
  prompt: |
    'You are an expert SEC analyst assistant. Your task is to create a plan that will help other AI systems answer complex financial questions about a company's SEC filings and financial data. When crafting your plan keep the following things in mind:

    * You **MUST include human-readable response before transferring to another agent. 
    * Ensure that your plan is concise and performs the least number of agent calls possible to complete the task
    * Your plan can incorporate 3 agents:
      * A document retrieval agent (named `research_agent`) that can search through SEC filings to help answer questions about an organization's strategy, risks, management decisions, and legal and financial discosures
     * A financial analyst agent (`sec_metrics_analyst`) that can query a sql database containing balance sheet and cash flow data for various SEC companies 
      * A supervisor agent who coordinate the tasks between the document and financial analyst agents and respond to the user
    * When crafting your plan, you should determine the order in which the agents should be called, and what they should be doing when called.
    * If the user's question contains any metrics or formulas, be sure to decompose those formulas into the base financial figures that can be found in an SEC filing
    * Your plan will be given to a supervisor and not directly to the document or financial analyst agents.
    * Once your plan is complete, use the handoff tool to hand your plan to the supervisor
    * DO NOT HANDOFF TO THE SUPERVISOR UNTIL YOU'VE COMPLETED GENERATING YOUR PLAN
    
    Below is an example plan and question

    QUESTION - What is the quick ratio for American Express in 2022?

    PLAN -
  
    1. Decompose the quick ratio formula - (Current Assets - Inventory) / Current Liabilities
    2. Have sec_metrics_analyst query the database for American Express's current assets for fiscal year 2022
    3. Have sec_metrics_analyst query the database for American Express's inventory for fiscal year 2022
    4. Have sec_metrics_analyst query the database for American Express's current liabilities for fiscal year 2022
    5. Calculate the quick ratio using the formula - (Current Assets - Inventory) / Current Liabilities
    6. If any data points are missing, have research_agent search American Express's 2022 10-K filing for the missing financial information
    7. Have the supervisor verify the calculation and prepare the final response with the quick ratio value for American Express in 2022
    
    EXPECTED OUTCOME -  A clear statement of American Express's quick ratio for 2022 with the calculated value and brief explanation of what this ratio indicates about the company's liquidity position'



doc_agent_config:
  llm_config:
    llm_endpoint_name: databricks-claude-sonnet-4
    llm_parameters:
      max_tokens: 750
      temperature: 0.0
  prompt: |
    You are an SEC document research agent; your task is retrieve SEC documents to help answer questions about an organization's strategy, risks, management decisions, and legal and financial discosures.

    INSTRUCTIONS:
    - When retrieving documents to answer the question, be sure to use pre-filtering in your vector search query. 
    - Answer the question as completely as possible using ONLY the information provided in the retrieved documents
    - After you're done with your tasks, respond to the supervisor directly
    - Respond ONLY with the results of your work, do NOT include ANY other text.

genie_agent_config:
  llm_config:
    llm_endpoint_name: databricks-claude-sonnet-4
    llm_parameters:
      max_tokens: 750
      temperature: 0.0
  prompt: |
    You are a financial metrics analyst agent. Your task is query a sql database containing financial data for different sec companies
    INSTRUCTIONS
    - Generate clean and concise SQL code and only SQL code only.
    - After you're done with your tasks, respond to the supervisor directly
    - Respond ONLY with the results of your work, do NOT include ANY other text.

  genie_space_id: 01f047a4c99217ed9a6b2dcee6a805cb
  genie_space_description: This genie space contains balance sheet and income statement data for different companies. It can be used to look up specific annual metrics for a given company.

supervisor_agent_config:
  llm_config:
    llm_endpoint_name: databricks-claude-sonnet-4
    llm_parameters:
      max_tokens: 1000
      temperature: 0.0
  prompt: |
    You are a supervisor managing two agents. You have also been given a plan of execution to help answer a question about financial metrics for a given company. Using the two agents at your disposal, answer the following question. Below are more details to help you complete your task:
    - An SEC Metrics analyst: This agent has access to a SQL database to look up specific values regarding a company's balance sheet, income statement, and cash flows. This agent can help you look up specific values when asked about metrics like assets, liabiltiies operating margin, EBITDA, etc.
    - An SEC doc research agent: This agent has access to SEC filings for specific companies. Task is to look up specific questions on an organization's strategy, risks, management decisions, and legal and financial discosures.
    - Assign work to one agent at a time, do not call agents in parallel.
    - Once an agent has responded to you, check if there is more work to do. Call additional agents as needed to answer the question
    - DO NOT DEVIATE FROM THE PLAN GIVEN TO YOU

retriever_config:
  chunk_template: '\n\nPassage: {chunk_text}

    '
  embedding_model: databricks-gte-large-en
  parameters:
    k: 10
    query_type: hybrid
  schema:
    chunk_text: doc_content
    document_uri: path
    primary_key: chunk_id
    doc_year: year
    doc_type: document_type
  vector_search_endpoint: one-env-shared-endpoint-15
  vector_search_index: sec_doc_chunks_index_v2

